### ISSUE TITLE
Dashboard showing linkage errors in commons-logging:commons-logging:1.2

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1871]
Part of #1863 

https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/16.1.0/com.google.http-client_google-http-client_1.38.0.html#linkage-errors

```
3 linkage error(s)

commons-logging:commons-logging:1.2
3 target classes causing linkage errors referenced from 3 source classes.

Class org.apache.avalon.framework.logger.Logger is not found, referenced from org.apache.commons.logging.impl.AvalonLogger

Class org.apache.log.Hierarchy is not found, referenced from org.apache.commons.logging.impl.LogKitLogger

Class org.apache.log.Logger is not found, referenced from org.apache.commons.logging.impl.LogKitLogger

The following paths contain commons-logging:commons-logging:1.2: ▼

com.google.cloud:google-cloud-bigquery:1.124.7 (compile) / commons-logging:commons-logging:1.2 (compile)
com.google.cloud:google-cloud-compute:0.119.0-alpha (compile) / commons-logging:commons-logging:1.2 (compile)
com.google.cloud:google-cloud-dns:1.0.5 (compile) / commons-logging:commons-logging:1.2 (compile)
```

Are they really problematic? If not we should not show them in the dashboard.

# AvalonLogger

[Javadoc: AvalongLogger](https://commons.apache.org/proper/commons-logging/apidocs/org/apache/commons/logging/impl/AvalonLogger.html)

> Implementation of commons-logging Log interface that delegates all logging calls to the Avalon logging abstraction: the Logger interface.

https://avalon.apache.org/closed.html says

> Apache Avalon has closed.

[commons-logging:1.2](https://search.maven.org/artifact/commons-logging/commons-logging/1.2/jar) declares avalong-framework as optional:

```
    <dependency>
      <groupId>avalon-framework</groupId>
      <artifactId>avalon-framework</artifactId>
      <version>4.1.5</version>
      <optional>true</optional>
    </dependency>
```

Maven does not include transitive optional dependencies. I don't see `org.apache.commons.logging.impl.AvalonLogger` catches NoClassDefFoundError to see the availability.

# LogKitLogger

[Javadoc: LogKitLogger](https://commons.apache.org/proper/commons-logging/apidocs/org/apache/commons/logging/impl/LogKitLogger.html):

> Implementation of org.apache.commons.logging.Log that wraps the avalon-logkit logging system.

The class has 2 invalid references: `org.apache.log.Hierarchy` and `org.apache.log.Logger`. Both classes are in logkit artifact. As per the Javadoc above, the logkit is part of the Avalon project.

`commons-logging:1.2` declares the dependency as optional. 

```
    <dependency>
      <groupId>logkit</groupId>
      <artifactId>logkit</artifactId>
      <version>1.0.1</version>
      <optional>false</optional>
    </dependency>
```

Maven does not include transitive optional dependencies. I don't see `org.apache.commons.logging.impl.LogKitLogger` catches NoClassDefFoundError to see the availability.

Are they reachable? No, they are not reachable from the artifacts in the Libraries BOM.

**Comment by elharo** [comment]
Why are they declared optional? How does commons-logging react when they're not in the classpath?

**Comment by suztomo** [comment]
> Why are they declared optional?

Because not all commons-logging users need Avalon and Logkit.

> How does commons-logging react when they're not in the classpath?

I didn't find any reference to the AvalonLogger or LogkitLogger from other classes in commons-logging. As per [commons-logging documentation on its configuration](https://commons.apache.org/proper/commons-logging/guide.html#Configuration), commons-logging users specify underlying logger implementation through property file, in which users can specify concrete class names such as `org.apache.commons.logging.impl.AvalonLogger` and `org.apache.commons.logging.impl.LogKitLogger`. I couldn't find the exact class names in commons-logging documents, probably because Avalon project had been closed when commons-logging 1.2 was released in 2014.

**Comment by elharo** [comment]
Surprisingly this project doesn't seem to be dormant.  We should send an issue and PR to them to remove Avalon and possibly LogKitLogger if they have not already done so.

**Comment by suztomo** [comment]
Sure. Let me file and issue and a pull request for commons-logging.

**Comment by suztomo** [comment]
@elharo Do you think it's a bad idea to show only reachable errors in the dashboard? I think the references to the unused logger classes are typical use cases for the reachability check.

**Comment by suztomo** [comment]
Discussed with Elliotte.

The entry point classes are the BOM members. How the suppressing unreachable linkage errors affect those who use declare dependencies to the transitive dependencies of BOM project?

It's better to suppress specific linkage errors rather than suppressing many unknowns.

Google-http-java-client's dependency comes from apache-http-client 4. The apache-http-client 5 does not depends on commons-logging.

Flattening the published pom.xml makes it difficult to identify where `commons-logging:commons-logging:1.2` is used in the BOM.

**Comment by elharo** [comment]
This is fixed, right?

**Comment by suztomo** [comment]
The errors are still there

<img width="1054" alt="Screen Shot 2021-07-22 at 09 33 49" src="https://user-images.githubusercontent.com/28604/126647699-875a2d90-06fb-43ef-a230-0a4d98c7cbf5.png">

**Comment by suztomo** [comment]
It's quite green now. The remaining problem is appengine-api-1.0-sdk and netty's shaded dependencies.
<img width="970" alt="Screen Shot 2021-08-10 at 10 57 11" src="https://user-images.githubusercontent.com/28604/128890233-893a867d-1106-4bee-ab53-96f5744ee6c1.png">
